name: 'Bit Command'
description: 'Execute a custom bit command'
branding: 
  icon: 'check'
  color: 'green'
inputs:
  cmd:
    description: "Custom command to execute"
    required: true
  ws-dir:
    description: "Workspace json file directory path"
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
